### ISSUE TITLE
Extend title definitions to beyond parameters in a flow definition

### ISSUE THREAD

**Issue by greg-wiltshire** [finos/tracdap#103]
### Description of Problem:
Currently in a flow definition the title property of a parameter can be set. Users may want to add bespoke titles in a flow (overriding and native title attribute of the object) for all objects in a flow.

### Potential Solutions:

- Add the ability to set titles to all object types used as inputs in a flow by extending the current definitions.
- Alternatively this could be restricted to just data objects which is where I see the greatest need.

**Comment by martin-traverse** [comment]
This was addressed in #311 and #334
