### ISSUE TITLE
Required and optional flow definition inputs

### ISSUE THREAD

**Issue by greg-wiltshire** [finos/tracdap#137]
Can the flow definition include whether a particular input is required or optional. This is useful in UIs for whether particular inputs need to be set or not.

**Comment by martin-traverse** [comment]
PR #442  addresses this issue - inputs and outputs can now be marked as optional in the defined_xxx() methods. To test if an optional input is supplied, use ctx.has_dataset(my_dataset). If an optional output is not required, the model doesn't need to output it. After a model completes, the runtime checks all the non-optional outputs have been provided, but it is fine if optional ones are missing.

Optional inputs and outputs can also be used in flows, either as flow inputs / outputs or to pass between models in the flow.

**Comment by martin-traverse** [comment]
Merged PR #442
