### ISSUE TITLE
Support for required and optional datasets in flow/model definition

### ISSUE THREAD

**Issue by greg-wiltshire** [finos/tracdap#224]
### Description of Problem:
In some calculations some datasets for a model or a flow may not be required by the code. An example would be to rely on default parameters/calculated values by default but to have the option of providing a dataset to trigger alternative logic flows. 

A second example would be when running a calculation that adds a snapshot or delta to a existing dataset. When this first runs the dataset to add to will not exist but will need to be specified from then on as one of the inputs. To enable this scenario the dataset needs to be set as optional.

### Potential Solutions:
Add to the flow and model definitions the ability to flag each input as optional/required.

**Comment by martin-traverse** [comment]
PR #442  addresses this issue - inputs and outputs can now be marked as optional in the defined_xxx() methods. To test if an optional input is supplied, use ctx.has_dataset(my_dataset). If an optional output is not required, the model doesn't need to output it. After a model completes, the runtime checks all the non-optional outputs have been provided, but it is fine if optional ones are missing.

Optional inputs and outputs can also be used in flows, either as flow inputs / outputs or to pass between models in the flow.

**Comment by martin-traverse** [comment]
Merged PR #442
