### ISSUE TITLE
Labels for nodes in flow definition

### ISSUE THREAD

**Issue by greg-wiltshire** [finos/tracdap#227]
### Description of Problem:
Showing human readable labels for model and input selections when defining a flow to run.

### Potential Solutions:
Add an optional string label property to the flow definition nodes to allow labels to be added and used when building a menu to set up a flow.

**Comment by martin-traverse** [comment]
I think we can just add a "label" field to all flow nodes. It can be left blank if not used and it won't be used for anything functional in the platform.
