### ISSUE TITLE
New metadata search operator: EXISTS

### ISSUE THREAD

**Issue by martin-traverse** [finos/tracdap#335]
TRAC metadata search currently supports these operations:

Equals, not equals, greater than, greater or equal, less than, less or equal and "in".

This feature is to add an "exists" operator to the set of metadata search operators. The "exists" operation should not care about the type or value of the attribute, only that there is an attribute with the matching name.

Search operators are defined in the search.proto metadata as SearchOperator and used in SearchTerm objects, which are passed to the DAL. Search terms can be combined in logical expressions.

The DAL search implementation is in JdbcSearchQueryBuilder, which builds a SQL query ffrom a metadata search expression. Each there is a "buildXXXTerm" method for each type of search operator. There are also mehods that combine these terms into logical expressions.

To add the exists operator we need another operator type in SearchOperators and a buildExistsTerm method in the query builder. The rest of the logic and should remain unaffected. Unit tests can be added at both the DAL level and metadata API level.

**Comment by pszajows** [comment]
Issue closed with PR #346.
