### ISSUE TITLE
Search API can not handle no search criteria

### ISSUE THREAD

**Issue by greg-wiltshire** [finos/tracdap#45]
When submitting a search API call with 

```
{
    "objectType": "FLOW",

    "search": {}
}
```
A 500 error is returned. The expected behaviour is that this (or some variant of this) would provide results for all flow objects in TRAC. Without this there is no way to discover what is in TRAC without first knowing the attributes and the values to search for.

**Comment by mslapek** [comment]
Is this error still present? 🤔 I think it was solved with #252

**Comment by martin-traverse** [comment]
This is a duplicate of #107, closed by #252.
